export default {
  // 加载频道列表
  CHANNELS_LOAD: 'CHANNELS_LOAD',
  CHANNELS_LOAD_SUCCESS: 'CHANNELS_LOAD_SUCCESS',
  CHANNELS_LOAD_ERROR: 'CHANNELS_LOAD_ERROR',

  // 加载单个频道下的新闻
  NEWS_LOAD: 'NEWS_LOAD',
  NEWS_LOAD_SUCCESS: 'NEWS_LOAD_SUCCESS',
  NEWS_LOAD_ERROR: 'NEWS_LOAD_ERROR',

  // 选中单个新闻
  SELECT_NEWS: 'SELECT_NEWS',

  // 输入关键词
  NEWS_SEARCH: 'NEWS_SEARCH'
};
